### ISSUE TITLE
About edges.txt

### ISSUE THREAD

**Issue by reyouww** [xzp9999/GMoD-mian#3]
edges.txt中描绘的是一个图结构，请问作者这个图的结构是怎么组织起来的？

**Comment by xzp9999** [comment]
在训练的第一阶段，先只做分类任务获取能表示疾病的embedding token，然后计算余弦相似度取Top-K构图
![image](https://github.com/user-attachments/assets/17ee1f9a-9791-4f48-a880-47446b950a4d)

**Comment by reyouww** [comment]
谢谢回复！
